### ISSUE TITLE
[Bug]: Official Stats section under HACKHAZARDS page is not responsive.

### ISSUE THREAD

**Issue by PranavBarthwal** [namespacecomm/NSCC-BPIT-Website#522]
### Describe the bug

Unresponsive Official Stats section under HACKHAZARDS page.

### To Reproduce

1. Go to HACKHAZARDS Page
2. Click inspect
3. Change dimensions of the page
4. The stats section gets distorted

### Expected Behavior

The section should be responsive in mobile, tablet and desktop view.

### Screenshot/ Video

![Screenshot 2024-05-18 134920](https://github.com/namespacecomm/NSCC-BPIT-Website/assets/110532770/6c0ff646-1a8c-4a57-87ac-58275fd71afb)
![Screenshot 2024-05-18 134948](https://github.com/namespacecomm/NSCC-BPIT-Website/assets/110532770/d967936a-dfb9-46b9-ae8d-7a71e61433bb)

**Comment by Gauranshgoel123** [comment]
pls assign me :)

**Comment by PranavBarthwal** [comment]
@Gauranshgoel123 updates?

**Comment by Gauranshgoel123** [comment]
will send PR by tonight

**Comment by Gauranshgoel123** [comment]
@PranavBarthwal pls review PR #524
